# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import products.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171209_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(location='protected'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
