# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
